import type { Neighborhood, SeedRestaurant } from './lib/types';

const seoulSggCodes = [
  '11110',
  '11140',
  '11170',
  '11200',
  '11215',
  '11230',
  '11260',
  '11290',
  '11305',
  '11320',
  '11350',
  '11380',
  '11410',
  '11440',
  '11470',
  '11500',
  '11530',
  '11545',
  '11560',
  '11590',
  '11620',
  '11650',
  '11680',
  '11710',
  '11740'
];

export const neighborhoods = [
  {
    id: 'seoul-all',
    name: '서울 전체',
    vibe: '대한민국 구석구석 맛집차트 기준 서울 25개 구의 인기 맛집을 한 번에 보는 지도',
    mapCenter: { lat: 37.5665, lng: 126.978, level: 8 },
    kakaoSearch: {
      query: '서울 맛집',
      radius: 20000,
      sort: 'distance'
    },
    visitKoreaChart: {
      ctpvNm: '서울특별시',
      sggCds: seoulSggCodes,
      categories: [],
      type: 1
    }
  },
  {
    id: 'seongsu',
    name: '성수',
    vibe: '공방과 팝업이 이어지는 골목에서 점심·저녁 후보를 발견하기 좋은 동네',
    mapCenter: { lat: 37.5442, lng: 127.0558, level: 4 },
    kakaoSearch: {
      query: '성수동 맛집',
      radius: 1500,
      sort: 'distance'
    },
    visitKoreaChart: {
      ctpvNm: '서울특별시',
      sggCds: ['11200'],
      categories: [],
      type: 1
    }
  },
  {
    id: 'mangwon',
    name: '망원',
    vibe: '시장권 생활 밀착형 맛집과 혼밥·간단한 술안주 후보가 많은 동네',
    mapCenter: { lat: 37.5567, lng: 126.9105, level: 4 },
    kakaoSearch: {
      query: '망원동 맛집',
      radius: 1500,
      sort: 'distance'
    },
    visitKoreaChart: {
      ctpvNm: '서울특별시',
      sggCds: ['11440'],
      categories: [],
      type: 1
    }
  },
  {
    id: 'euljiro',
    name: '을지로',
    vibe: '노포와 힙한 가게가 섞여 있어 가성비 신호를 비교하기 좋은 동네',
    mapCenter: { lat: 37.5663, lng: 126.9924, level: 4 },
    kakaoSearch: {
      query: '을지로 맛집',
      radius: 1500,
      sort: 'distance'
    },
    visitKoreaChart: {
      ctpvNm: '서울특별시',
      sggCds: ['11140'],
      categories: [],
      type: 1
    }
  },
  {
    id: 'gwangjin',
    name: '광진구',
    vibe: '건대입구와 어린이대공원 주변까지 외식 후보를 넓게 비교하기 좋은 동네',
    mapCenter: { lat: 37.5481, lng: 127.0857, level: 5 },
    kakaoSearch: {
      query: '광진구 맛집',
      radius: 2000,
      sort: 'distance'
    },
    visitKoreaChart: {
      ctpvNm: '서울특별시',
      sggCds: ['11215'],
      categories: [],
      type: 1
    }
  },
  {
    id: 'dongdaemun',
    name: '동대문구',
    vibe: '청량리와 회기 생활권을 중심으로 점심·저녁 후보를 찾기 좋은 동네',
    mapCenter: { lat: 37.5744, lng: 127.0396, level: 5 },
    kakaoSearch: {
      query: '동대문구 맛집',
      radius: 2000,
      sort: 'distance'
    },
    visitKoreaChart: {
      ctpvNm: '서울특별시',
      sggCds: ['11230'],
      categories: [],
      type: 1
    }
  },
  {
    id: 'naver-shared',
    name: '네이버 저장 맛집',
    vibe: '공유받은 네이버 지도 저장목록 맛집 422곳을 한 번에 보는 컬렉션',
    mapCenter: { lat: 37.5665, lng: 126.978, level: 8 }
  }
] satisfies Neighborhood[];

export const restaurants = [
  {
    id: 'seongsu-galbi-jip',
    neighborhoodId: 'seongsu',
    name: '성수 갈비집',
    category: '한식',
    avgMealPrice: 11000,
    tasteScore: 8.9,
    evidenceCount: 82,
    blogMentions: 24,
    positiveReviewRatio: 0.93,
    x: 26,
    y: 62,
    specialties: ['점심정식', '돼지갈비', '된장찌개'],
    note: '점심 피크가 빠르고 반찬 구성이 좋아 재방문 근거가 많은 곳.'
  },
  {
    id: 'seongsu-noodle-lab',
    neighborhoodId: 'seongsu',
    name: '누들랩 성수',
    category: '면요리',
    avgMealPrice: 9500,
    tasteScore: 8.4,
    evidenceCount: 71,
    blogMentions: 18,
    positiveReviewRatio: 0.91,
    x: 48,
    y: 28,
    specialties: ['비빔면', '온면', '수육'],
    note: '가격 대비 구성과 회전이 좋아 점심 콘텐츠 후보로 안정적이다.'
  },
  {
    id: 'seongsu-market-table',
    neighborhoodId: 'seongsu',
    name: '시장앞 식탁',
    category: '백반',
    avgMealPrice: 8500,
    tasteScore: 8.1,
    evidenceCount: 63,
    blogMentions: 13,
    positiveReviewRatio: 0.9,
    x: 66,
    y: 54,
    specialties: ['백반', '제육볶음', '생선구이'],
    note: '가성비 키워드 빈도가 높고 직장인 재방문 언급이 많다.'
  },
  {
    id: 'seongsu-charcoal-diner',
    neighborhoodId: 'seongsu',
    name: '숯불식당 성수',
    category: '고기',
    avgMealPrice: 15000,
    tasteScore: 9.1,
    evidenceCount: 95,
    blogMentions: 31,
    positiveReviewRatio: 0.94,
    x: 77,
    y: 34,
    specialties: ['숯불불고기', '한우국밥', '냉면'],
    note: '가격대는 살짝 있지만 맛 만족도와 근거량이 아주 강하다.'
  },
  {
    id: 'seongsu-bap-bar',
    neighborhoodId: 'seongsu',
    name: '밥바 성수',
    category: '덮밥',
    avgMealPrice: 9800,
    tasteScore: 8.2,
    evidenceCount: 58,
    blogMentions: 16,
    positiveReviewRatio: 0.88,
    x: 39,
    y: 72,
    specialties: ['스테이크덮밥', '연어덮밥'],
    note: '비주얼이 좋아 블로그 소재화하기 쉽다는 언급이 잦다.'
  },
  {
    id: 'seongsu-rice-club',
    neighborhoodId: 'seongsu',
    name: '쌀클럽',
    category: '퓨전',
    avgMealPrice: 13500,
    tasteScore: 8.6,
    evidenceCount: 49,
    blogMentions: 21,
    positiveReviewRatio: 0.89,
    x: 58,
    y: 81,
    specialties: ['버터라이스', '명란파스타'],
    note: '후기 수는 중간이지만 블로그 노출 대비 반응이 좋다.'
  },
  {
    id: 'mangwon-market-soup',
    neighborhoodId: 'mangwon',
    name: '망원시장 국밥',
    category: '국밥',
    avgMealPrice: 9000,
    tasteScore: 8.5,
    evidenceCount: 88,
    blogMentions: 19,
    positiveReviewRatio: 0.92,
    x: 22,
    y: 48,
    specialties: ['돼지국밥', '수육백반'],
    note: '시장 상권 특유의 생활형 후기와 재방문 후기 양이 많다.'
  },
  {
    id: 'mangwon-fried-fish',
    neighborhoodId: 'mangwon',
    name: '망원 생선튀김',
    category: '분식',
    avgMealPrice: 7000,
    tasteScore: 7.9,
    evidenceCount: 67,
    blogMentions: 11,
    positiveReviewRatio: 0.9,
    x: 41,
    y: 31,
    specialties: ['생선튀김', '오징어튀김'],
    note: '가격 경쟁력이 높아 간식형 포스팅 후보로 좋다.'
  },
  {
    id: 'mangwon-noodle-house',
    neighborhoodId: 'mangwon',
    name: '망원면옥',
    category: '칼국수',
    avgMealPrice: 8000,
    tasteScore: 8.3,
    evidenceCount: 74,
    blogMentions: 15,
    positiveReviewRatio: 0.91,
    x: 63,
    y: 52,
    specialties: ['칼국수', '만두'],
    note: '한 끼 만족도와 저렴한 세트 구성이 자주 언급된다.'
  },
  {
    id: 'mangwon-bbq-alley',
    neighborhoodId: 'mangwon',
    name: '망원불향거리',
    category: '고기',
    avgMealPrice: 13000,
    tasteScore: 8.8,
    evidenceCount: 92,
    blogMentions: 28,
    positiveReviewRatio: 0.93,
    x: 74,
    y: 36,
    specialties: ['직화제육', '불막창'],
    note: '맛 만족도와 후기량이 모두 높아 메인 포스팅용으로 강력하다.'
  },
  {
    id: 'mangwon-night-snack',
    neighborhoodId: 'mangwon',
    name: '밤야식 포차',
    category: '주점',
    avgMealPrice: 12000,
    tasteScore: 8.1,
    evidenceCount: 61,
    blogMentions: 20,
    positiveReviewRatio: 0.87,
    x: 81,
    y: 67,
    specialties: ['닭목살구이', '우동'],
    note: '야식형 포스팅 소재로 쓰기 좋다는 언급이 많다.'
  },
  {
    id: 'mangwon-home-meal',
    neighborhoodId: 'mangwon',
    name: '집밥집 망원',
    category: '백반',
    avgMealPrice: 8500,
    tasteScore: 8.0,
    evidenceCount: 56,
    blogMentions: 9,
    positiveReviewRatio: 0.89,
    x: 54,
    y: 79,
    specialties: ['가정식백반', '고등어구이'],
    note: '가성비·혼밥 키워드가 반복돼 기본기가 탄탄하다.'
  },
  {
    id: 'euljiro-roast-house',
    neighborhoodId: 'euljiro',
    name: '을지 직화집',
    category: '직화구이',
    avgMealPrice: 12000,
    tasteScore: 8.7,
    evidenceCount: 97,
    blogMentions: 29,
    positiveReviewRatio: 0.94,
    x: 28,
    y: 40,
    specialties: ['직화제육', '불오징어'],
    note: '후기량과 만족도가 모두 높고 점심·저녁 확장성이 좋다.'
  },
  {
    id: 'euljiro-no-pocha',
    neighborhoodId: 'euljiro',
    name: '을지로 노포포차',
    category: '주점',
    avgMealPrice: 14000,
    tasteScore: 8.9,
    evidenceCount: 84,
    blogMentions: 35,
    positiveReviewRatio: 0.92,
    x: 49,
    y: 24,
    specialties: ['닭도리탕', '계란말이'],
    note: '노포 감성과 가성비를 함께 언급한 콘텐츠가 많다.'
  },
  {
    id: 'euljiro-lunch-counter',
    neighborhoodId: 'euljiro',
    name: '점심카운터 을지',
    category: '덮밥',
    avgMealPrice: 9500,
    tasteScore: 8.2,
    evidenceCount: 69,
    blogMentions: 12,
    positiveReviewRatio: 0.9,
    x: 67,
    y: 55,
    specialties: ['항정덮밥', '닭구이정식'],
    note: '혼밥과 점심 회전 만족도가 높아 실사용성이 좋다.'
  },
  {
    id: 'euljiro-noodle-archive',
    neighborhoodId: 'euljiro',
    name: '면보관소',
    category: '국수',
    avgMealPrice: 8500,
    tasteScore: 8.0,
    evidenceCount: 57,
    blogMentions: 14,
    positiveReviewRatio: 0.88,
    x: 76,
    y: 73,
    specialties: ['잔치국수', '비빔국수'],
    note: '가격 메리트가 커서 가벼운 추천글에 적합하다.'
  },
  {
    id: 'euljiro-fried-rice-factory',
    neighborhoodId: 'euljiro',
    name: '볶음공장',
    category: '중식',
    avgMealPrice: 10000,
    tasteScore: 8.4,
    evidenceCount: 73,
    blogMentions: 17,
    positiveReviewRatio: 0.91,
    x: 56,
    y: 82,
    specialties: ['차돌볶음밥', '마파두부'],
    note: '가격 대비 만족도가 높고 직장인 후기 비중이 높다.'
  },
  {
    id: 'euljiro-heritage-stew',
    neighborhoodId: 'euljiro',
    name: '유산찌개',
    category: '찌개',
    avgMealPrice: 11500,
    tasteScore: 8.6,
    evidenceCount: 64,
    blogMentions: 22,
    positiveReviewRatio: 0.9,
    x: 36,
    y: 68,
    specialties: ['김치찌개', '계란말이'],
    note: '전통적인 메뉴 조합에 대한 만족 댓글이 꾸준하다.'
  },
  {
    id: 'gwangjin-ashley-queens-guui',
    neighborhoodId: 'gwangjin',
    name: '애슐리퀸즈 구의이스트폴점',
    category: '패밀리레스토랑',
    avgMealPrice: 19900,
    tasteScore: 8.3,
    evidenceCount: 100,
    blogMentions: 30,
    positiveReviewRatio: 0.92,
    x: 56,
    y: 58,
    lat: 37.53671721896844,
    lng: 127.08789463681796,
    roadAddressName: '서울 광진구 아차산로 402',
    addressName: '서울 광진구 아차산로 402',
    specialties: ['뷔페', '패밀리레스토랑'],
    note: '대한민국 구석구석 맛집차트 광진구 현지인 랭킹 후보.'
  },
  {
    id: 'gwangjin-starbucks-guui-dt',
    neighborhoodId: 'gwangjin',
    name: '스타벅스 구의DT점',
    category: '커피전문점',
    avgMealPrice: 7000,
    tasteScore: 7.9,
    evidenceCount: 94,
    blogMentions: 28,
    positiveReviewRatio: 0.9,
    x: 54,
    y: 43,
    lat: 37.5452992590491,
    lng: 127.087195778352,
    roadAddressName: '서울 광진구 광나루로 519',
    addressName: '서울 광진구 광나루로 519',
    specialties: ['커피', '디저트'],
    note: '대한민국 구석구석 맛집차트 광진구 현지인 랭킹 후보.'
  },
  {
    id: 'gwangjin-songrim-restaurant',
    neighborhoodId: 'gwangjin',
    name: '송림식당 [한식]',
    category: '한식',
    avgMealPrice: 12000,
    tasteScore: 8.8,
    evidenceCount: 88,
    blogMentions: 26,
    positiveReviewRatio: 0.93,
    x: 33,
    y: 58,
    lat: 37.53669435709824,
    lng: 127.07636141622157,
    roadAddressName: '서울 광진구 자양번영로 79',
    addressName: '서울 광진구 자양번영로 79',
    specialties: ['한식', '식사'],
    note: '대한민국 구석구석 맛집차트 광진구 현지인 랭킹 후보.'
  },
  {
    id: 'gwangjin-on-the-bread',
    neighborhoodId: 'gwangjin',
    name: '온더브레드 광진점',
    category: '제과점',
    avgMealPrice: 9000,
    tasteScore: 8.1,
    evidenceCount: 82,
    blogMentions: 24,
    positiveReviewRatio: 0.9,
    x: 82,
    y: 42,
    lat: 37.54582455777235,
    lng: 127.10295587513612,
    roadAddressName: '서울 광진구 천호대로 801',
    addressName: '서울 광진구 천호대로 801',
    specialties: ['베이커리', '커피'],
    note: '대한민국 구석구석 맛집차트 광진구 현지인 랭킹 후보.'
  },
  {
    id: 'gwangjin-hamheung-naengmyeon-kondae',
    neighborhoodId: 'gwangjin',
    name: '함흥본가면옥 건대점',
    category: '한식',
    avgMealPrice: 11000,
    tasteScore: 8.5,
    evidenceCount: 76,
    blogMentions: 22,
    positiveReviewRatio: 0.91,
    x: 40,
    y: 43,
    lat: 37.54516319002332,
    lng: 127.07985097444919,
    roadAddressName: '서울 광진구 광나루로 456',
    addressName: '서울 광진구 광나루로 456',
    specialties: ['냉면', '한식'],
    note: '대한민국 구석구석 맛집차트 광진구 현지인 랭킹 후보.'
  },
  {
    id: 'gwangjin-songdo-galbi',
    neighborhoodId: 'gwangjin',
    name: '송도갈비 광장점',
    category: '한식',
    avgMealPrice: 18000,
    tasteScore: 8.6,
    evidenceCount: 70,
    blogMentions: 20,
    positiveReviewRatio: 0.91,
    x: 80,
    y: 41,
    lat: 37.54634681902709,
    lng: 127.10198293989964,
    roadAddressName: '서울 광진구 천호대로 793',
    addressName: '서울 광진구 천호대로 793',
    specialties: ['갈비', '한식'],
    note: '대한민국 구석구석 맛집차트 광진구 현지인 랭킹 후보.'
  },
  {
    id: 'dongdaemun-dining-one-cheongnyangni',
    neighborhoodId: 'dongdaemun',
    name: '다이닝원 청량리점',
    category: '부페',
    avgMealPrice: 19900,
    tasteScore: 8.2,
    evidenceCount: 100,
    blogMentions: 30,
    positiveReviewRatio: 0.91,
    x: 57,
    y: 45,
    lat: 37.5772704990008,
    lng: 127.043034207749,
    roadAddressName: '서울 동대문구 고산자로32길 78',
    addressName: '서울 동대문구 고산자로32길 78',
    specialties: ['뷔페', '가족외식'],
    note: '대한민국 구석구석 맛집차트 동대문구 현지인 랭킹 후보.'
  },
  {
    id: 'dongdaemun-hongneung-galbi',
    neighborhoodId: 'dongdaemun',
    name: '홍능갈비집 본점',
    category: '한식',
    avgMealPrice: 16000,
    tasteScore: 8.8,
    evidenceCount: 94,
    blogMentions: 28,
    positiveReviewRatio: 0.93,
    x: 56,
    y: 29,
    lat: 37.58689614035988,
    lng: 127.0425576808745,
    roadAddressName: '서울 동대문구 제기로 85',
    addressName: '서울 동대문구 제기로 85',
    specialties: ['갈비', '한식'],
    note: '대한민국 구석구석 맛집차트 동대문구 현지인 랭킹 후보.'
  },
  {
    id: 'dongdaemun-burgerking-jangan',
    neighborhoodId: 'dongdaemun',
    name: '버거킹 장안SK점',
    category: '패스트푸드',
    avgMealPrice: 9000,
    tasteScore: 7.8,
    evidenceCount: 88,
    blogMentions: 26,
    positiveReviewRatio: 0.88,
    x: 87,
    y: 56,
    lat: 37.570171364178904,
    lng: 127.06499748448584,
    roadAddressName: '서울 동대문구 한천로 100',
    addressName: '서울 동대문구 한천로 100',
    specialties: ['버거', '패스트푸드'],
    note: '대한민국 구석구석 맛집차트 동대문구 현지인 랭킹 후보.'
  },
  {
    id: 'dongdaemun-ilmi-gejang',
    neighborhoodId: 'dongdaemun',
    name: '일미간장게장 본점',
    category: '전문음식점',
    avgMealPrice: 18000,
    tasteScore: 8.7,
    evidenceCount: 82,
    blogMentions: 24,
    positiveReviewRatio: 0.92,
    x: 95,
    y: 55,
    lat: 37.5708682974026,
    lng: 127.071421767987,
    roadAddressName: '서울 동대문구 장한로24길 7',
    addressName: '서울 동대문구 장한로24길 7',
    specialties: ['간장게장', '한식'],
    note: '대한민국 구석구석 맛집차트 동대문구 현지인 랭킹 후보.'
  },
  {
    id: 'dongdaemun-kfc-jeonnong',
    neighborhoodId: 'dongdaemun',
    name: 'KFC 전농동점',
    category: '패스트푸드',
    avgMealPrice: 9000,
    tasteScore: 7.7,
    evidenceCount: 76,
    blogMentions: 22,
    positiveReviewRatio: 0.87,
    x: 78,
    y: 48,
    lat: 37.5754067062954,
    lng: 127.057948125287,
    roadAddressName: '서울 동대문구 전농로 118',
    addressName: '서울 동대문구 전농로 118',
    specialties: ['치킨', '패스트푸드'],
    note: '대한민국 구석구석 맛집차트 동대문구 현지인 랭킹 후보.'
  },
  {
    id: 'dongdaemun-eomeoni-daesungjip',
    neighborhoodId: 'dongdaemun',
    name: '어머니대성집',
    category: '한식',
    avgMealPrice: 12000,
    tasteScore: 8.5,
    evidenceCount: 70,
    blogMentions: 20,
    positiveReviewRatio: 0.91,
    x: 35,
    y: 45,
    lat: 37.57751310069622,
    lng: 127.02854772845984,
    roadAddressName: '서울 동대문구 왕산로11길 4',
    addressName: '서울 동대문구 왕산로11길 4',
    specialties: ['해장국', '한식'],
    note: '대한민국 구석구석 맛집차트 동대문구 현지인 랭킹 후보.'
  }
] satisfies SeedRestaurant[];
