export const neighborhoods = [
  {
    id: 'seongsu',
    name: '성수',
    vibe: '공방과 팝업 사이에 숨어 있는 점심·저녁 후보를 빠르게 훑기 좋은 동네',
    mapCenter: { lat: 37.5442, lng: 127.0558, level: 4 },
    kakaoSearch: {
      query: '성수동 맛집',
      radius: 1500,
      sort: 'distance'
    }
  },
  {
    id: 'mangwon',
    name: '망원',
    vibe: '시장권 생활 밀착형 맛집과 혼밥·간단한 술안주 후보가 많은 동네',
    mapCenter: { lat: 37.5567, lng: 126.9105, level: 4 },
    kakaoSearch: {
      query: '망원동 맛집',
      radius: 1500,
      sort: 'distance'
    }
  },
  {
    id: 'euljiro',
    name: '을지로',
    vibe: '노포와 힙한 가게가 섞여 있어 가성비 신호를 비교하기 좋은 동네',
    mapCenter: { lat: 37.5663, lng: 126.9924, level: 4 },
    kakaoSearch: {
      query: '을지로 맛집',
      radius: 1500,
      sort: 'distance'
    }
  }
];

export const restaurants = [
  {
    id: 'seongsu-galbi-jip',
    neighborhoodId: 'seongsu',
    name: '성수 갈비집',
    category: '한식',
    avgMealPrice: 11000,
    tasteScore: 8.9,
    evidenceCount: 82,
    blogMentions: 24,
    positiveReviewRatio: 0.93,
    x: 26,
    y: 62,
    specialties: ['점심정식', '돼지갈비', '된장찌개'],
    note: '점심 피크가 빠르고 반찬 구성이 좋아 재방문 근거가 많은 곳.'
  },
  {
    id: 'seongsu-noodle-lab',
    neighborhoodId: 'seongsu',
    name: '누들랩 성수',
    category: '면요리',
    avgMealPrice: 9500,
    tasteScore: 8.4,
    evidenceCount: 71,
    blogMentions: 18,
    positiveReviewRatio: 0.91,
    x: 48,
    y: 28,
    specialties: ['비빔면', '온면', '수육'],
    note: '가격 대비 구성과 회전이 좋아 점심 콘텐츠 후보로 안정적이다.'
  },
  {
    id: 'seongsu-market-table',
    neighborhoodId: 'seongsu',
    name: '시장앞 식탁',
    category: '백반',
    avgMealPrice: 8500,
    tasteScore: 8.1,
    evidenceCount: 63,
    blogMentions: 13,
    positiveReviewRatio: 0.9,
    x: 66,
    y: 54,
    specialties: ['백반', '제육볶음', '생선구이'],
    note: '가성비 키워드 빈도가 높고 직장인 재방문 언급이 많다.'
  },
  {
    id: 'seongsu-charcoal-diner',
    neighborhoodId: 'seongsu',
    name: '숯불식당 성수',
    category: '고기',
    avgMealPrice: 15000,
    tasteScore: 9.1,
    evidenceCount: 95,
    blogMentions: 31,
    positiveReviewRatio: 0.94,
    x: 77,
    y: 34,
    specialties: ['숯불불고기', '한우국밥', '냉면'],
    note: '가격대는 살짝 있지만 맛 만족도와 근거량이 아주 강하다.'
  },
  {
    id: 'seongsu-bap-bar',
    neighborhoodId: 'seongsu',
    name: '밥바 성수',
    category: '덮밥',
    avgMealPrice: 9800,
    tasteScore: 8.2,
    evidenceCount: 58,
    blogMentions: 16,
    positiveReviewRatio: 0.88,
    x: 39,
    y: 72,
    specialties: ['스테이크덮밥', '연어덮밥'],
    note: '비주얼이 좋아 블로그 소재화하기 쉽다는 언급이 잦다.'
  },
  {
    id: 'seongsu-rice-club',
    neighborhoodId: 'seongsu',
    name: '쌀클럽',
    category: '퓨전',
    avgMealPrice: 13500,
    tasteScore: 8.6,
    evidenceCount: 49,
    blogMentions: 21,
    positiveReviewRatio: 0.89,
    x: 58,
    y: 81,
    specialties: ['버터라이스', '명란파스타'],
    note: '후기 수는 중간이지만 블로그 노출 대비 반응이 좋다.'
  },
  {
    id: 'mangwon-market-soup',
    neighborhoodId: 'mangwon',
    name: '망원시장 국밥',
    category: '국밥',
    avgMealPrice: 9000,
    tasteScore: 8.5,
    evidenceCount: 88,
    blogMentions: 19,
    positiveReviewRatio: 0.92,
    x: 22,
    y: 48,
    specialties: ['돼지국밥', '수육백반'],
    note: '시장 상권 특유의 생활형 후기와 재방문 후기 양이 많다.'
  },
  {
    id: 'mangwon-fried-fish',
    neighborhoodId: 'mangwon',
    name: '망원 생선튀김',
    category: '분식',
    avgMealPrice: 7000,
    tasteScore: 7.9,
    evidenceCount: 67,
    blogMentions: 11,
    positiveReviewRatio: 0.9,
    x: 41,
    y: 31,
    specialties: ['생선튀김', '오징어튀김'],
    note: '가격 경쟁력이 높아 간식형 포스팅 후보로 좋다.'
  },
  {
    id: 'mangwon-noodle-house',
    neighborhoodId: 'mangwon',
    name: '망원면옥',
    category: '칼국수',
    avgMealPrice: 8000,
    tasteScore: 8.3,
    evidenceCount: 74,
    blogMentions: 15,
    positiveReviewRatio: 0.91,
    x: 63,
    y: 52,
    specialties: ['칼국수', '만두'],
    note: '한 끼 만족도와 저렴한 세트 구성이 자주 언급된다.'
  },
  {
    id: 'mangwon-bbq-alley',
    neighborhoodId: 'mangwon',
    name: '망원불향거리',
    category: '고기',
    avgMealPrice: 13000,
    tasteScore: 8.8,
    evidenceCount: 92,
    blogMentions: 28,
    positiveReviewRatio: 0.93,
    x: 74,
    y: 36,
    specialties: ['직화제육', '불막창'],
    note: '맛 만족도와 후기량이 모두 높아 메인 포스팅용으로 강력하다.'
  },
  {
    id: 'mangwon-night-snack',
    neighborhoodId: 'mangwon',
    name: '밤야식 포차',
    category: '주점',
    avgMealPrice: 12000,
    tasteScore: 8.1,
    evidenceCount: 61,
    blogMentions: 20,
    positiveReviewRatio: 0.87,
    x: 81,
    y: 67,
    specialties: ['닭목살구이', '우동'],
    note: '야식형 포스팅 소재로 쓰기 좋다는 언급이 많다.'
  },
  {
    id: 'mangwon-home-meal',
    neighborhoodId: 'mangwon',
    name: '집밥집 망원',
    category: '백반',
    avgMealPrice: 8500,
    tasteScore: 8.0,
    evidenceCount: 56,
    blogMentions: 9,
    positiveReviewRatio: 0.89,
    x: 54,
    y: 79,
    specialties: ['가정식백반', '고등어구이'],
    note: '가성비·혼밥 키워드가 반복돼 기본기가 탄탄하다.'
  },
  {
    id: 'euljiro-roast-house',
    neighborhoodId: 'euljiro',
    name: '을지 직화집',
    category: '직화구이',
    avgMealPrice: 12000,
    tasteScore: 8.7,
    evidenceCount: 97,
    blogMentions: 29,
    positiveReviewRatio: 0.94,
    x: 28,
    y: 40,
    specialties: ['직화제육', '불오징어'],
    note: '후기량과 만족도가 모두 높고 점심·저녁 확장성이 좋다.'
  },
  {
    id: 'euljiro-no-pocha',
    neighborhoodId: 'euljiro',
    name: '을지로 노포포차',
    category: '주점',
    avgMealPrice: 14000,
    tasteScore: 8.9,
    evidenceCount: 84,
    blogMentions: 35,
    positiveReviewRatio: 0.92,
    x: 49,
    y: 24,
    specialties: ['닭도리탕', '계란말이'],
    note: '노포 감성과 가성비를 함께 언급한 콘텐츠가 많다.'
  },
  {
    id: 'euljiro-lunch-counter',
    neighborhoodId: 'euljiro',
    name: '점심카운터 을지',
    category: '덮밥',
    avgMealPrice: 9500,
    tasteScore: 8.2,
    evidenceCount: 69,
    blogMentions: 12,
    positiveReviewRatio: 0.9,
    x: 67,
    y: 55,
    specialties: ['항정덮밥', '닭구이정식'],
    note: '혼밥과 점심 회전 만족도가 높아 실사용성이 좋다.'
  },
  {
    id: 'euljiro-noodle-archive',
    neighborhoodId: 'euljiro',
    name: '면보관소',
    category: '국수',
    avgMealPrice: 8500,
    tasteScore: 8.0,
    evidenceCount: 57,
    blogMentions: 14,
    positiveReviewRatio: 0.88,
    x: 76,
    y: 73,
    specialties: ['잔치국수', '비빔국수'],
    note: '가격 메리트가 커서 가벼운 추천글에 적합하다.'
  },
  {
    id: 'euljiro-fried-rice-factory',
    neighborhoodId: 'euljiro',
    name: '볶음공장',
    category: '중식',
    avgMealPrice: 10000,
    tasteScore: 8.4,
    evidenceCount: 73,
    blogMentions: 17,
    positiveReviewRatio: 0.91,
    x: 56,
    y: 82,
    specialties: ['차돌볶음밥', '마파두부'],
    note: '가격 대비 만족도가 높고 직장인 후기 비중이 높다.'
  },
  {
    id: 'euljiro-heritage-stew',
    neighborhoodId: 'euljiro',
    name: '유산찌개',
    category: '찌개',
    avgMealPrice: 11500,
    tasteScore: 8.6,
    evidenceCount: 64,
    blogMentions: 22,
    positiveReviewRatio: 0.9,
    x: 36,
    y: 68,
    specialties: ['김치찌개', '계란말이'],
    note: '전통적인 메뉴 조합에 대한 만족 댓글이 꾸준하다.'
  }
];
